apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | lower }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/Configmap.yaml") . | sha256sum }}
        {{- if .Values.service.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/scheme: {{ .Values.service.metrics.scheme | quote }}
        prometheus.io/path: {{ .Values.service.metrics.path | quote }}
        prometheus.io/port: {{ $.Values.port | quote }}
        {{- end }}
      labels:
        {{- include "labels" . | nindent 8 }}
        app.kubernetes.io/service: backend
    spec:
      terminationGracePeriodSeconds: 60 # put your longest Job time here plus security time.
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.registry }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http-backend
              containerPort: {{ $.Values.port }}
              protocol: TCP
          {{- if .Values.consulSidecar.enabled }}
          env:
            - name: CONSUL_HTTP_ADDR
              value: "http://127.0.0.1:8500"
            - name: CONSUL_GRPC_ADDR
              value: "127.0.0.1:8502"
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "fullname" $ }}-env
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | default "/metrics" }}
              port: {{ $.Values.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | default "/metrics" }}
              port: {{ $.Values.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.consulSidecar.enabled }}
        - name: consul
          image: hashicorp/consul:latest
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "agent"
            - "-retry-join={{ .Values.consulSidecar.hosts | join " " }}"
            - "-advertise=$(POD_IP)"
            - "-client=0.0.0.0"
            - "-datacenter=dc1"
            - "-data-dir=/consul/data"
            - "-config-dir=/consul/config"
            - "-enable-local-script-checks"
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8600
              name: dns
              protocol: UDP
            - containerPort: 8301
              name: serf-wan
            - containerPort: 8302
              name: serf-lan
              protocol: UDP
          volumeMounts:
            - name: consul-data
              mountPath: /consul/data
        {{- end }}
      imagePullSecrets:
        {{- if .Values.image.imagePullSecrets.create }}
        - name: {{ include "fullname" $ }}-img
        {{- else if .Values.image.imagePullSecrets.name }}
        - name: {{ .Values.image.imagePullSecrets.name }}
        {{- end }}
        - name: {{ include "fullname" $ }}-img
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.consulSidecar.enabled }}
      volumes:
        - name: consul-data
          emptyDir: {}
      {{- end }}
