{{- if .Values.image.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" $ }}-img
  labels:
    {{- include "labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "dockerconfigjson" . | b64enc | quote }}
{{- end }}