---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-service
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ $.Values.port }}
      targetPort: {{ $.Values.port }}
      protocol: TCP
      name: http-backend
    {{- if .Values.consulSidecar.enabled }}
    - name: http
      port: 8500
      protocol: TCP
    - name: dns
      port: 8600
      protocol: UDP
    - name: serf-wan
      port: 8301
      protocol: UDP
    - name: serf-lan
      port: 8302
      protocol: UDP
    {{- end }}
    {{- if .Values.debug.enabled }}
    - name: debug
      port: 2345
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/service: backend

